<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="LAPTOP-42QT06F9" failures="2" tests="8" name="Test" time="67.278" errors="0" timestamp="2025-03-23T19:25:19 IST">
  <testcase classname="testCases.TC001_AccountRegistrationTest" name="verify_account_registration" time="4.278"/>
  <testcase classname="testCases.TC002_LoginTest" name="verify_login" time="1.735"/>
  <testcase classname="testCases.TC003_LoginDDT" name="verify_loginDDT" time="2.167"/>
  <testcase classname="testCases.TC003_LoginDDT" name="verify_loginDDT" time="11.198"/>
  <testcase classname="testCases.TC003_LoginDDT" name="verify_loginDDT" time="11.23"/>
  <testcase classname="testCases.TC003_LoginDDT" name="verify_loginDDT" time="10.885">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at testCases.TC003_LoginDDT.verify_loginDDT(TC003_LoginDDT.java:50)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- verify_loginDDT -->
  <testcase classname="testCases.TC003_LoginDDT" name="verify_loginDDT" time="11.231"/>
  <testcase classname="testCases.TC003_LoginDDT" name="verify_loginDDT" time="1.219">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at testCases.TC003_LoginDDT.verify_loginDDT(TC003_LoginDDT.java:50)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- verify_loginDDT -->
</testsuite> <!-- Test -->
